# ============================================================================
# Database PostgreSQL - Keeper K8s Injector Demo
# ============================================================================
#
# This example shows how to inject PostgreSQL credentials from Keeper.
# Demonstrates credential rotation without pod restarts!
#
# QUICK START:
#   1. Create a "postgres-credentials" record in Keeper with login/password
#   2. kubectl apply -f database-postgres.yaml
#   3. kubectl port-forward svc/db-client 8080:80
#   4. Open http://localhost:8080
#
# WHAT'S INCLUDED:
#   - PostgreSQL: Demo database server
#   - Database Client: App that connects to PostgreSQL using Keeper credentials
#
# ============================================================================

# ----------------------------------------------------------------------------
# PostgreSQL Database (Demo Instance)
# ----------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: postgres-init-password
type: Opaque
stringData:
  # Initial password - the app will use Keeper for credentials
  POSTGRES_PASSWORD: "initial-password-change-me"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "demouser"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-init-password
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "demodb"
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "demouser", "-d", "demodb"]
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres

---
# ----------------------------------------------------------------------------
# Database Client App with Keeper Credential Injection
# ----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-client
  labels:
    app: db-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-client
  template:
    metadata:
      labels:
        app: db-client
      annotations:
        # Enable Keeper injection
        keeper.security/inject: "true"

        # Reference to your KSM auth secret
        keeper.security/auth-secret: "keeper-credentials"

        # Use YAML config to specify .env format (no jq needed!)
        keeper.security/config: |
          secrets:
            - record: postgres-credentials
              path: /keeper/secrets/postgres-credentials.env
              format: env

        # Check for credential updates every minute
        keeper.security/refresh-interval: "60s"
    spec:
      containers:
      - name: app
        image: postgres:15-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: scripts
          mountPath: /scripts
        command:
        - /bin/sh
        - -c
        - |
          # Install nginx
          apk add --no-cache nginx > /dev/null 2>&1

          # Create nginx directories
          mkdir -p /run/nginx /var/lib/nginx/tmp

          # No dependencies needed! Using .env format
          # Function to read credentials from Keeper secret
          get_creds() {
            if [ -f "/keeper/secrets/postgres-credentials.env" ]; then
              # Source the .env file to load variables
              export $(grep -v '^#' /keeper/secrets/postgres-credentials.env | xargs)
              DB_USER="${LOGIN:-${USERNAME:-demouser}}"
              DB_PASS="${PASSWORD:-initial-password-change-me}"
            else
              DB_USER="demouser"
              DB_PASS="initial-password-change-me"
            fi
          }

          # Function to test database connection
          test_connection() {
            get_creds
            export PGPASSWORD="$DB_PASS"
            RESULT=$(psql -h postgres -U "$DB_USER" -d demodb -c "SELECT 'Connected at ' || NOW() as status;" -t 2>&1)
            echo "$RESULT"
          }

          # Update page function
          update_page() {
            get_creds
            TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
            CONN_STATUS=$(test_connection)
            CONN_SUCCESS=$(echo "$CONN_STATUS" | grep -c "Connected at" || echo "0")

            if [ "$CONN_SUCCESS" -gt 0 ]; then
              STATUS_COLOR="#4CAF50"
              STATUS_TEXT="✅ Connected"
              STATUS_DETAIL="$CONN_STATUS"
            else
              STATUS_COLOR="#f44336"
              STATUS_TEXT="❌ Connection Failed"
              STATUS_DETAIL="$CONN_STATUS"
            fi

            # Generate HTML response
            cat > /usr/share/nginx/html/index.html << HTMLEOF
          <!DOCTYPE html>
          <html>
          <head>
            <title>PostgreSQL Connection Demo</title>
            <meta http-equiv="refresh" content="5">
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                background: #f5f5f5;
              }
              .card {
                background: white;
                border-radius: 12px;
                padding: 30px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                margin-bottom: 20px;
              }
              .status {
                padding: 20px;
                border-radius: 8px;
                text-align: center;
                color: white;
                font-size: 1.5em;
                background: ${STATUS_COLOR};
              }
              .details {
                background: #1a1a2e;
                color: #00ff88;
                padding: 15px;
                border-radius: 8px;
                font-family: monospace;
                margin-top: 20px;
                white-space: pre-wrap;
              }
              .creds {
                background: #f0f0f0;
                padding: 15px;
                border-radius: 8px;
                margin-top: 15px;
              }
              .masked {
                color: #666;
                font-style: italic;
              }
              h1 { margin-top: 0; }
              .timestamp { color: #666; font-size: 14px; margin-top: 15px; }
            </style>
          </head>
          <body>
            <div class="card">
              <h1>🐘 PostgreSQL Connection Demo</h1>
              <p>This app reads database credentials from Keeper and connects to PostgreSQL.</p>

              <div class="status">${STATUS_TEXT}</div>

              <div class="details">${STATUS_DETAIL}</div>

              <div class="creds">
                <strong>Credentials from Keeper:</strong><br>
                Username: <code>${DB_USER}</code><br>
                Password: <span class="masked">[hidden - ${#DB_PASS} characters]</span>
              </div>

              <p class="timestamp">Last check: ${TIMESTAMP}</p>
              <p class="timestamp">Page auto-refreshes every 5 seconds</p>
            </div>

            <div class="card">
              <h3>🔄 Try Credential Rotation</h3>
              <ol>
                <li>Update the password in your <strong>"postgres-credentials"</strong> Keeper record</li>
                <li>Also update the PostgreSQL password: <code>kubectl exec -it deploy/postgres -- psql -U demouser -d demodb -c "ALTER USER demouser PASSWORD 'newpassword';"</code></li>
                <li>Watch this page reconnect with the new credentials!</li>
              </ol>
            </div>
          </body>
          </html>
          HTMLEOF
          }

          # Initial page generation
          update_page

          # Background job to refresh the page every 5 seconds
          while true; do
            sleep 5
            update_page
          done &

          # Start nginx
          nginx -g 'daemon off;'
      volumes:
      - name: html
        emptyDir: {}
      - name: scripts
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db-client
  labels:
    app: db-client
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: db-client
