# PostgreSQL Database
# This is a simple PostgreSQL instance for demo purposes.
# In production, you'd use a managed database service.

apiVersion: v1
kind: Secret
metadata:
  name: postgres-init-password
type: Opaque
stringData:
  # Initial password - the app will use Keeper for credentials
  POSTGRES_PASSWORD: "initial-password-change-me"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "demouser"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-init-password
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "demodb"
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "demouser", "-d", "demodb"]
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
