apiVersion: v1
kind: Pod
metadata:
  name: basic-k8s-secret-demo
  annotations:
    # Enable injection
    keeper.security/inject: "true"
    keeper.security/auth-secret: "keeper-credentials"

    # Enable K8s Secret injection
    keeper.security/inject-as-k8s-secret: "true"
    keeper.security/k8s-secret-name: "app-secrets"

    # Specify which Keeper record to use
    keeper.security/secret: "demo-secret"
spec:
  containers:
    - name: app
      image: nginx:alpine
      env:
        # Reference K8s Secret keys
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: password

      # Can also mount as volume
      volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true

  volumes:
    - name: secrets
      secret:
        secretName: app-secrets
