apiVersion: v1
kind: Pod
metadata:
  name: custom-keys-demo
  annotations:
    keeper.security/inject: "true"
    keeper.security/auth-secret: "keeper-credentials"

    # YAML config with custom key mapping
    keeper.security/config: |
      secrets:
        - record: "postgres-credentials"
          injectAsK8sSecret: true
          k8sSecretName: "db-credentials"
          k8sSecretKeys:
            username: "POSTGRES_USER"
            password: "POSTGRES_PASSWORD"
            host: "POSTGRES_HOST"
            port: "POSTGRES_PORT"
spec:
  containers:
    - name: app
      image: postgres:16
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_HOST
