apiVersion: v1
kind: Pod
metadata:
  name: tls-secret-demo
  annotations:
    keeper.security/inject: "true"
    keeper.security/ksm-config: "keeper-credentials"

    # Create TLS Secret from Keeper record with file attachments
    keeper.security/config: |
      secrets:
        - record: "TLS Certificate"
          fileName: "cert.pem"
          injectAsK8sSecret: true
          k8sSecretName: "tls-cert"
          k8sSecretType: "kubernetes.io/tls"
          k8sSecretKeys:
            tls.crt: "cert.pem"
            tls.key: "key.pem"
spec:
  containers:
    - name: app
      image: nginx:alpine
      volumeMounts:
        - name: tls
          mountPath: /etc/nginx/ssl
          readOnly: true

  volumes:
    - name: tls
      secret:
        secretName: tls-cert

---
# Can also be used with Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-ingress-demo
spec:
  tls:
    - hosts:
        - example.com
      secretName: tls-cert
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-service
                port:
                  number: 80
