# Kubernetes ServiceAccount with Azure Workload Identity annotation
#
# Replace CLIENT_ID with your Azure managed identity client ID

apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa
  namespace: default
  annotations:
    # Azure managed identity client ID
    azure.workload.identity/client-id: "CLIENT_ID"
