# ============================================================================
# TLS NGINX - Keeper K8s Injector Demo
# ============================================================================
#
# Demonstrates TLS certificate management using Keeper file attachments.
# Certificates rotate automatically without pod restart!
#
# QUICK START:
#   1. Upload cert.pem and key.pem as file attachments to a Keeper record
#   2. kubectl apply -f tls-nginx.yaml
#   3. kubectl port-forward svc/nginx-tls 8443:443
#   4. Open https://localhost:8443 (accept self-signed warning)
#
# WHAT'S INCLUDED:
#   - ConfigMap: NGINX TLS configuration
#   - Deployment: NGINX server with TLS certificates from Keeper
#
# ============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-tls-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      server {
        listen 443 ssl;
        server_name localhost;

        # TLS certificates from Keeper
        ssl_certificate /app/certs/server.crt;
        ssl_certificate_key /app/certs/server.key;

        # TLS settings
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
          root /usr/share/nginx/html;
          index index.html;
        }

        location /health {
          access_log off;
          return 200 "OK\n";
          add_header Content-Type text/plain;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tls
  labels:
    app: nginx-tls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-tls
  template:
    metadata:
      labels:
        app: nginx-tls
      annotations:
        # Enable Keeper injection
        keeper.security/inject: "true"
        # Reference to your KSM auth secret
        keeper.security/ksm-config: "keeper-credentials"
        # Inject TLS certificate files from Keeper record
        # Format: keeper.security/file-{name}: "{record-title}:{filename}:{path}"
        keeper.security/file-cert: "tls-certificate:server.crt:/app/certs/server.crt"
        keeper.security/file-key: "tls-certificate:server.key:/app/certs/server.key"
        # Check for certificate updates every 12 hours
        keeper.security/refresh-interval: "12h"
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 443
          name: https
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: html
          mountPath: /usr/share/nginx/html
        command:
        - /bin/sh
        - -c
        - |
          # Create status page
          cat > /usr/share/nginx/html/index.html << 'HTMLEOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>TLS Demo</title>
            <meta http-equiv="refresh" content="30">
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                background: #f5f5f5;
              }
              .card {
                background: white;
                border-radius: 12px;
                padding: 30px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                margin-bottom: 20px;
              }
              .success {
                background: #4CAF50;
                color: white;
                padding: 20px;
                border-radius: 8px;
                text-align: center;
                font-size: 1.5em;
                margin: 20px 0;
              }
              h1 { margin-top: 0; }
              code {
                background: #1a1a2e;
                color: #00ff88;
                padding: 4px 8px;
                border-radius: 4px;
                font-family: monospace;
              }
              .cert-info {
                background: #f0f0f0;
                padding: 15px;
                border-radius: 8px;
                font-family: monospace;
                font-size: 13px;
                white-space: pre;
              }
              .info {
                background: #e3f2fd;
                border-left: 4px solid #2196F3;
                padding: 15px;
                margin-top: 20px;
              }
            </style>
            <script>
              // Display certificate info
              window.onload = function() {
                if (window.location.protocol === 'https:') {
                  document.getElementById('tls-status').innerHTML = '🔒 TLS Connection Active';
                }
              }
            </script>
          </head>
          <body>
            <div class="card">
              <h1>🔐 NGINX TLS Demo</h1>
              <p>This page is served over HTTPS using TLS certificates from Keeper.</p>

              <div class="success" id="tls-status">
                ✅ TLS Working!
              </div>

              <h3>Certificate Details</h3>
              <div class="cert-info">
          Certificate: /app/certs/server.crt
          Private Key: /app/certs/server.key
          Managed by: Keeper Secrets Manager
              </div>
            </div>

            <div class="card info">
              <h3>🔄 Certificate Rotation</h3>
              <p>When you update the certificate files in Keeper:</p>
              <ol>
                <li>The sidecar detects the change (checks every 12 hours)</li>
                <li>New certificate files are written to <code>/app/certs/</code></li>
                <li>NGINX picks up the new certificates automatically</li>
                <li><strong>No pod restart required!</strong></li>
              </ol>
            </div>

            <div class="card">
              <h3>📋 Setup Instructions</h3>
              <p>In your Keeper vault:</p>
              <ol>
                <li>Create a record titled <strong>"tls-certificate"</strong></li>
                <li>Attach your certificate as <strong>server.crt</strong></li>
                <li>Attach your private key as <strong>server.key</strong></li>
              </ol>
              <p><em>For testing, you can generate self-signed certificates:</em></p>
              <code style="display:block; padding:10px; margin-top:10px;">
          openssl req -x509 -newkey rsa:4096 -nodes \
            -keyout server.key -out server.crt \
            -days 365 -subj "/CN=localhost"
              </code>
            </div>
          </body>
          </html>
          HTMLEOF

          # Wait for certificates to be injected
          echo "Waiting for TLS certificates..."
          until [ -f /app/certs/server.crt ] && [ -f /app/certs/server.key ]; do
            sleep 2
          done
          echo "Certificates found! Starting NGINX..."

          # Start nginx
          nginx -g 'daemon off;'
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-tls-config
      - name: html
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-tls
  labels:
    app: nginx-tls
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-tls
