# Pod with Secret Rotation
# Sidecar continuously refreshes secrets at the specified interval
apiVersion: v1
kind: Pod
metadata:
  name: my-app-rotation
  annotations:
    keeper.security/inject: "true"
    keeper.security/auth-secret: "keeper-auth"
    keeper.security/secret: "api-credentials"
    # Refresh secrets every 5 minutes
    keeper.security/refresh-interval: "5m"
    # Optional: Send SIGHUP to app container on refresh
    keeper.security/signal: "SIGHUP"
spec:
  containers:
    - name: app
      image: alpine:latest
      command:
        - sh
        - -c
        - |
          # Simple app that watches for file changes
          echo "Starting app..."
          while true; do
            echo "Current secret content:"
            cat /keeper/secrets/api-credentials.json
            echo ""
            echo "Waiting for changes..."
            sleep 60
          done
