# ============================================================================
# AWS Secrets Manager - Keeper K8s Injector Demo
# ============================================================================
#
# Example using AWS Secrets Manager for KSM config storage.
# No static credentials in Kubernetes - uses IRSA!
#
# QUICK START:
#   1. Store KSM config in AWS Secrets Manager
#   2. Create IAM role with Secrets Manager access
#   3. Update aws-secret-id and aws-region below
#   4. kubectl apply -f aws-secrets-manager.yaml
#   5. kubectl logs deployment/aws-secrets-example
#
# WHAT'S INCLUDED:
#   - ServiceAccount: With IAM role annotation for IRSA
#   - Deployment: App that fetches KSM config from AWS Secrets Manager
#
# ============================================================================

# ----------------------------------------------------------------------------
# ServiceAccount with AWS IAM Role Annotation
# ----------------------------------------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa
  namespace: default
  annotations:
    # IAM role that can access AWS Secrets Manager
    # REPLACE: ACCOUNT_ID and keeper-secrets-access with your values
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/keeper-secrets-access

---
# ----------------------------------------------------------------------------
# Deployment with AWS Secrets Manager Integration
# ----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-secrets-example
  labels:
    app: aws-secrets-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-secrets-example
  template:
    metadata:
      labels:
        app: aws-secrets-example
      annotations:
        # Enable Keeper injection
        keeper.security/inject: "true"

        # Use AWS Secrets Manager for KSM config
        keeper.security/auth-method: "aws-secrets-manager"

        # REPLACE: Update these with your AWS Secrets Manager details
        keeper.security/aws-secret-id: "prod/keeper/ksm-config"
        keeper.security/aws-region: "us-west-2"

        # Secret to inject (from Keeper)
        keeper.security/secret: "demo-secret"

        # Refresh interval
        keeper.security/refresh-interval: "5m"
    spec:
      # IMPORTANT: Use ServiceAccount with IAM role
      serviceAccountName: myapp-sa

      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        command:
        - /bin/sh
        - -c
        - |
          echo "Keeper K8s Injector - AWS Secrets Manager Example"
          echo ""
          echo "This pod fetches its KSM configuration from AWS Secrets Manager"
          echo "using IRSA (IAM Roles for Service Accounts)."
          echo ""
          echo "No static credentials stored in Kubernetes!"
          echo ""

          # Wait for secret to be injected
          while [ ! -f /keeper/secrets/demo-secret.json ]; do
            echo "Waiting for secret injection..."
            sleep 2
          done

          echo "Secret successfully injected!"
          echo ""
          echo "Secret file: /keeper/secrets/demo-secret.json"
          ls -lah /keeper/secrets/

          # Keep container running
          tail -f /dev/null
---
apiVersion: v1
kind: Service
metadata:
  name: aws-secrets-example
  labels:
    app: aws-secrets-example
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: aws-secrets-example
