# Kubernetes ServiceAccount with AWS IAM Role annotation
#
# Replace ACCOUNT_ID and keeper-secrets-access with your values

apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa
  namespace: default
  annotations:
    # IAM role that can access AWS Secrets Manager
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/keeper-secrets-access
