# ============================================================================
# GCP Secret Manager - Keeper K8s Injector Demo
# ============================================================================
#
# Example using GCP Secret Manager for KSM config storage.
# No static credentials in Kubernetes - uses Workload Identity!
#
# QUICK START:
#   1. Store KSM config in GCP Secret Manager
#   2. Create GCP service account with Secret Manager access
#   3. Configure Workload Identity binding
#   4. Update gcp-secret-id below with your project ID
#   5. kubectl apply -f gcp-secret-manager.yaml
#
# WHAT'S INCLUDED:
#   - ServiceAccount: With Workload Identity annotation
#   - Deployment: App that fetches KSM config from GCP Secret Manager
#
# ============================================================================

# ----------------------------------------------------------------------------
# ServiceAccount with GCP Workload Identity Annotation
# ----------------------------------------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa
  namespace: default
  annotations:
    # GCP service account with Secret Manager access
    # REPLACE: PROJECT_ID with your GCP project ID
    iam.gke.io/gcp-service-account: keeper-secrets-access@PROJECT_ID.iam.gserviceaccount.com

---
# ----------------------------------------------------------------------------
# Deployment with GCP Secret Manager Integration
# ----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-secrets-example
  labels:
    app: gcp-secrets-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-secrets-example
  template:
    metadata:
      labels:
        app: gcp-secrets-example
      annotations:
        # Enable Keeper injection
        keeper.security/inject: "true"

        # Use GCP Secret Manager for KSM config
        keeper.security/auth-method: "gcp-secret-manager"

        # REPLACE: Update PROJECT_ID with your GCP project ID
        keeper.security/gcp-secret-id: "projects/PROJECT_ID/secrets/ksm-config/versions/latest"

        # Secret to inject
        keeper.security/secret: "demo-secret"
        keeper.security/refresh-interval: "5m"
    spec:
      # Use ServiceAccount with Workload Identity
      serviceAccountName: myapp-sa

      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        command:
        - /bin/sh
        - -c
        - |
          echo "Keeper K8s Injector - GCP Secret Manager Example"
          echo "KSM config fetched from GCP Secret Manager using Workload Identity"

          while [ ! -f /keeper/secrets/demo-secret.json ]; do
            echo "Waiting for secret injection..."
            sleep 2
          done

          echo "Secret injected successfully!"
          ls -lah /keeper/secrets/
          tail -f /dev/null
