# Kubernetes ServiceAccount with GCP Workload Identity annotation
#
# Replace PROJECT_ID with your GCP project ID

apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa
  namespace: default
  annotations:
    # GCP service account with Secret Manager access
    iam.gke.io/gcp-service-account: keeper-secrets-access@PROJECT_ID.iam.gserviceaccount.com
